model:
  backbone: resnet18
  pretrained: true
  freeze_backbone: false

training:
  epochs: 25
  batch_size: 32
  learning_rate: 0.0001
  img_size: 128
  num_workers: 0

paths:
  dataset_dir: data/dataset/UTKFace
  model_output: age_gender_model.pth

device:
  use_cuda: true
